export const getColorCode = (name) => {
    if (!name) return '#000';
    const colors = {
        'Martini Racing': '#ffffff', // Primary white with livery
        'Grey Alcantara': '#4a4a4a',
        'Pearl White': '#fcfaf0',
        'Carmine Red': '#a50021',
        'Brooklyn Grey': '#8e918f',
        'Midnight Blue': '#191970',
        'Rosso Corsa': '#d40000',
        'Obsidian Black': '#0b0b0b',
        'Alfa Red': '#b00000',
        'Fuji White': '#fcfcfc',
        'Light Oyster': '#d1d1d1',
        'Jet Black Metallic': '#050505',
        'Luxor Beige': '#d2b48c',
        'Suzuka Grey': '#dcdcdc',
        'Torch Red': '#ff0000',
        'Adrenaline Red': '#e60000',
        'Grabber Blue': '#00aae4',
        'Black Onyx': '#0f0f0f',
        'Infrared': '#8b0000',
        'Toasted Caramel': '#8b5a2b',
        'Polar Silver': '#bcbcbc',
        'Le Mans Blue': '#000080',
        'Blue-Black Metallic': '#0a0a1a',
        'Bayside Blue': '#0047ab',
        'Grey Cloth': '#808080',
        'Formula Red': '#cc0000',
        'Renaissance Red': '#cc0000',
        'Titanium Grey': '#565e5e',
        'Mars Red': '#ad0e0e',
        'Checkered Cloth': '#333333',
        'Signature Black': '#000000',
        'Boticelli Leather': '#3d2b1f',
        'Solid Fire Red': '#c21807',
        'Black': '#000000',
        'Dual Tone': '#808080',
        'Foliage Green': '#4a5d23',
        'Black and Beige': '#d5c4a1',
        'Red Rage': '#cc0000',
        'Radiant Red Metallic': '#b30000',
        'Beige Leather': '#f5f5dc',
        'Super White': '#ffffff',
        'Camel Brown Leather': '#c19a6b',
        'Glacier White Pearl': '#f8f9fa',
        'Diamond White': '#fffafa',
        'Black & Golden': '#332f2c',
        'White': '#ffffff',
        'Black and Grey': '#555555',
        'blue & black': '#1e3f66',
        'Cosmic Gold': '#c5b358',
        'Oyster White': '#e3d6c1',
        'Midnight Black': '#111111',
        'Light Beige': '#f5f5dc',
        'Abyss Black': '#0a0a0a',
        'Grey/Black Two-Tone': '#4a4a4a',
        'Nexa Blue': '#003366',
        'Bordeaux and Black': '#4d0011',
        'Matte Graphite': '#36454f',
        'Sage Green': '#77815c',
        'Pearl White with Black Roof': '#f0ebd8',
        'Black & Maroon': '#800000',
        'Glaze Red': '#8b0000',
        'Oak White and Black': '#e8e4c9',
        'Crystal Blue': '#5cb3ff',
        'Beige/Black': '#d1bfae',
        'Phoenix Orange': '#ff7f00',
        'Brown/Black': '#5c4033',
        'Tornado Blue': '#1f4788',
        'Grey/Black': '#555555',
        'Crimson Red': '#dc143c',
        'Aurora Silver': '#c0c0c0',
        'Crystal White': '#f8f8ff',
        'Foliage Blue': '#223a5e',
        'Beige': '#f5f5dc',
        'Black and White': '#ffffff',
        'Black Leather': '#1a1a1a',
        'Silver': '#c0c0c0',
        'Grey': '#808080',
        'Gray': '#808080',
        'Blue': '#0000ff',
        'Red': '#ff0000',
        'Typhoon Silver': '#c0c0c0',
        'Autumn Orange': '#ff8c00',
        'Metallic Red': '#b22222',
        'Imperial Blue': '#002366',
        'Flare Garnet Red': '#7e191b',
        'Honey Orange': '#ffbd33',
        'Persimmon Red': '#ec5800',
        'Titan Grey': '#565e60',
        'Flame Red': '#e25822',
        'Olive Green Metallic': '#3d5229',
        'Metal Mustard': '#daa520',
        'Sportin Red': '#ff0000'
    };
    const normalized = Object.keys(colors).find(k => k.toLowerCase() === name.toLowerCase());
    return normalized ? colors[normalized] : name;
};
