version: '3.8'
# Override file for private testing
# Usage: docker-compose -f docker-compose.yml -f docker-compose.private.yml up --build
services:
  backend:
    container_name: trailblazeauto-backend-private
    ports:
      - "8001:8000"
    environment:
      - DEBUG=1
      - SQLITE_DB_NAME=/tmp/db_private.sqlite3
      - INIT_SCRIPT=scripts.seed_private
    volumes:
      - trailblazeauto_private_uploads:/app/uploads
      - sqlite_private_data:/app/db_data
volumes:
  trailblazeauto_private_uploads:
  sqlite_private_data:

