# Override file for private testing
# Usage: docker compose -f ../base-app/docker-compose.yml -f docker-compose.private.yml up --build

services:
  postgres:
    environment:
      POSTGRES_USER: trailblaze
      POSTGRES_PASSWORD: "trailblazepass"
      POSTGRES_DB: trailblaze_private
    volumes:
      - trailblazeauto_postgres_data_private:/var/lib/postgresql/data

  backend:
    environment:
      - INIT_SCRIPT=scripts.seed_private
      - DATABASE_URL=postgresql://trailblaze:trailblazepass@postgres:5432/trailblaze_private

volumes:
  trailblazeauto_postgres_data_private: